; Generated; do not hand-edit.

ProofLine0G0:
        byte $00,$44,$44,$44,$4C,$54,$64,$44
ProofLine0G1:
        byte $00,$44,$44,$44,$7C,$44,$44,$38
ProofLine0G2:
        byte $00,$78,$04,$04,$38,$40,$40,$3C
ProofLine0G3:
        byte $00,$44,$44,$44,$7C,$44,$44,$38
ProofLine0G4:
        byte $00,$00,$00,$00,$00,$00,$00,$00
ProofLine0G5:
        byte $00,$00,$00,$00,$00,$00,$00,$00

ProofLine1G0:
        byte $00,$38,$44,$40,$40,$40,$44,$38
ProofLine1G1:
        byte $00,$38,$44,$44,$44,$44,$44,$38
ProofLine1G2:
        byte $00,$44,$44,$44,$4C,$54,$64,$44
ProofLine1G3:
        byte $00,$10,$10,$10,$10,$10,$10,$7C
ProofLine1G4:
        byte $00,$44,$48,$50,$78,$44,$44,$78
ProofLine1G5:
        byte $00,$38,$44,$44,$44,$44,$44,$38

ProofLine2G0:
        byte $00,$7C,$40,$40,$40,$40,$40,$40
ProofLine2G1:
        byte $00,$00,$00,$00,$00,$00,$00,$00
ProofLine2G2:
        byte $00,$00,$00,$00,$00,$00,$00,$00
ProofLine2G3:
        byte $00,$00,$00,$00,$00,$00,$00,$00
ProofLine2G4:
        byte $00,$00,$00,$00,$00,$00,$00,$00
ProofLine2G5:
        byte $00,$00,$00,$00,$00,$00,$00,$00

ProofLine3G0:
        byte $00,$44,$44,$44,$54,$54,$6C,$44
ProofLine3G1:
        byte $00,$44,$44,$44,$7C,$44,$44,$38
ProofLine3G2:
        byte $00,$38,$44,$44,$04,$04,$04,$04
ProofLine3G3:
        byte $00,$38,$44,$44,$44,$44,$44,$38
ProofLine3G4:
        byte $00,$44,$48,$50,$78,$44,$44,$78
ProofLine3G5:
        byte $00,$00,$00,$00,$00,$00,$00,$00

ProofLine4G0:
        byte $00,$10,$10,$10,$10,$10,$10,$7C
ProofLine4G1:
        byte $00,$38,$44,$44,$44,$44,$44,$38
ProofLine4G2:
        byte $00,$44,$44,$44,$54,$54,$6C,$44
ProofLine4G3:
        byte $00,$00,$00,$00,$00,$00,$00,$00
ProofLine4G4:
        byte $00,$00,$00,$00,$00,$00,$00,$00
ProofLine4G5:
        byte $00,$00,$00,$00,$00,$00,$00,$00

ProofLine5G0:
        byte $00,$78,$04,$04,$38,$40,$40,$3C
ProofLine5G1:
        byte $00,$44,$44,$44,$7C,$44,$44,$38
ProofLine5G2:
        byte $00,$10,$10,$10,$10,$10,$10,$7C
ProofLine5G3:
        byte $00,$7C,$40,$40,$78,$40,$40,$7C
ProofLine5G4:
        byte $00,$7C,$40,$40,$40,$40,$40,$40
ProofLine5G5:
        byte $00,$7C,$40,$40,$40,$40,$40,$40

ProofLine6G0:
        byte $00,$7C,$10,$10,$10,$10,$10,$7C
ProofLine6G1:
        byte $00,$10,$10,$10,$10,$10,$10,$7C
ProofLine6G2:
        byte $00,$7C,$40,$40,$78,$40,$40,$7C
ProofLine6G3:
        byte $00,$78,$04,$04,$38,$40,$40,$3C
ProofLine6G4:
        byte $00,$00,$00,$00,$00,$00,$00,$00
ProofLine6G5:
        byte $00,$00,$00,$00,$00,$00,$00,$00

ProofLine0:
        byte <ProofLine0G0,>ProofLine0G0,<ProofLine0G1,>ProofLine0G1,<ProofLine0G2,>ProofLine0G2,<ProofLine0G3,>ProofLine0G3,<ProofLine0G4,>ProofLine0G4,<ProofLine0G5,>ProofLine0G5

ProofLine1:
        byte <ProofLine1G0,>ProofLine1G0,<ProofLine1G1,>ProofLine1G1,<ProofLine1G2,>ProofLine1G2,<ProofLine1G3,>ProofLine1G3,<ProofLine1G4,>ProofLine1G4,<ProofLine1G5,>ProofLine1G5

ProofLine2:
        byte <ProofLine2G0,>ProofLine2G0,<ProofLine2G1,>ProofLine2G1,<ProofLine2G2,>ProofLine2G2,<ProofLine2G3,>ProofLine2G3,<ProofLine2G4,>ProofLine2G4,<ProofLine2G5,>ProofLine2G5

ProofLine3:
        byte <ProofLine3G0,>ProofLine3G0,<ProofLine3G1,>ProofLine3G1,<ProofLine3G2,>ProofLine3G2,<ProofLine3G3,>ProofLine3G3,<ProofLine3G4,>ProofLine3G4,<ProofLine3G5,>ProofLine3G5

ProofLine4:
        byte <ProofLine4G0,>ProofLine4G0,<ProofLine4G1,>ProofLine4G1,<ProofLine4G2,>ProofLine4G2,<ProofLine4G3,>ProofLine4G3,<ProofLine4G4,>ProofLine4G4,<ProofLine4G5,>ProofLine4G5

ProofLine5:
        byte <ProofLine5G0,>ProofLine5G0,<ProofLine5G1,>ProofLine5G1,<ProofLine5G2,>ProofLine5G2,<ProofLine5G3,>ProofLine5G3,<ProofLine5G4,>ProofLine5G4,<ProofLine5G5,>ProofLine5G5

ProofLine6:
        byte <ProofLine6G0,>ProofLine6G0,<ProofLine6G1,>ProofLine6G1,<ProofLine6G2,>ProofLine6G2,<ProofLine6G3,>ProofLine6G3,<ProofLine6G4,>ProofLine6G4,<ProofLine6G5,>ProofLine6G5
