; Generated; do not hand-edit.

Page0Line0G0:
        byte $00,$AA,$AA,$EA,$EE,$EA,$EA,$A4
Page0Line0G1:
        byte $00,$CA,$2A,$2A,$4E,$8A,$8A,$64
Page0Line0G2:
        byte $00,$06,$08,$08,$08,$08,$08,$06
Page0Line0G3:
        byte $00,$4A,$AA,$AE,$AE,$AE,$AE,$4A
Page0Line0G4:
        byte $00,$4A,$4A,$4C,$4C,$4A,$4A,$EC
Page0Line0G5:
        byte $00,$4E,$A8,$A8,$A8,$A8,$A8,$48

Page0Line1G0:
        byte $00,$44,$4A,$4A,$4A,$4A,$4A,$E4
Page0Line1G1:
        byte $00,$0A,$0A,$0A,$0A,$0E,$0E,$0A
Page0Line1G2:
        byte $00,$A4,$AA,$AA,$E2,$A2,$A2,$42
Page0Line1G3:
        byte $00,$4A,$AA,$AC,$AC,$AA,$AA,$4C
Page0Line1G4:
        byte $00,$04,$04,$04,$04,$04,$04,$0E
Page0Line1G5:
        byte $00,$4A,$AA,$AA,$AA,$AE,$AE,$4A

Page0Line2G0:
        byte $00,$AE,$E8,$E8,$AC,$A8,$A8,$AE
Page0Line2G1:
        byte $00,$0A,$0E,$0E,$0A,$0A,$0A,$0A
Page0Line2G2:
        byte $00,$EE,$48,$48,$48,$48,$48,$E8
Page0Line2G3:
        byte $00,$E0,$80,$80,$80,$80,$80,$80
Page0Line2G4:
        byte $00,$4C,$A2,$A2,$A4,$A8,$A8,$A6
Page0Line2G5:
        byte $00,$E0,$80,$80,$C0,$80,$80,$E0

Page0Line3G0:
        byte $00,$CA,$2A,$2A,$4E,$8A,$8A,$64
Page0Line3G1:
        byte $00,$4E,$48,$48,$4C,$48,$48,$EE
Page0Line3G2:
        byte $00,$EE,$88,$88,$88,$88,$88,$88
Page0Line3G3:
        byte $00,$E4,$44,$44,$44,$44,$44,$EE
Page0Line3G4:
        byte $00,$EC,$82,$82,$C4,$88,$88,$E6
Page0Line3G5:
        byte $00,$00,$00,$00,$00,$00,$00,$00

Page0Line4G0:
        byte $00,$44,$4A,$4A,$4A,$4A,$4A,$E4
Page0Line4G1:
        byte $00,$06,$08,$08,$08,$08,$08,$06
Page0Line4G2:
        byte $00,$4A,$AA,$AE,$AE,$AE,$AE,$4A
Page0Line4G3:
        byte $00,$4A,$4A,$4C,$4C,$4A,$4A,$EC
Page0Line4G4:
        byte $00,$4E,$A8,$A8,$A8,$A8,$A8,$48
Page0Line4G5:
        byte $00,$00,$00,$00,$00,$00,$00,$00

Page0Line5G0:
        byte $00,$44,$4A,$4A,$4A,$4A,$AA,$A4
Page0Line5G1:
        byte $00,$4A,$AA,$AC,$AC,$AA,$AA,$AC
Page0Line5G2:
        byte $00,$04,$0A,$0A,$0A,$0A,$0A,$04
Page0Line5G3:
        byte $00,$AC,$AA,$CA,$CC,$AA,$AA,$CC
Page0Line5G4:
        byte $00,$E4,$44,$44,$44,$44,$44,$EE
Page0Line5G5:
        byte $00,$40,$00,$00,$00,$00,$00,$00

Page1Line0G0:
        byte $00,$8E,$88,$88,$C8,$A8,$A8,$C8
Page1Line0G1:
        byte $00,$A4,$A4,$A4,$E4,$A4,$AA,$4A
Page1Line0G2:
        byte $00,$EA,$8A,$8C,$CC,$8A,$8A,$EC
Page1Line0G3:
        byte $00,$00,$40,$40,$00,$40,$40,$00
Page1Line0G4:
        byte $00,$44,$4A,$4A,$4A,$4A,$AA,$A4
Page1Line0G5:
        byte $00,$40,$A0,$A0,$A0,$A0,$A0,$A0

Page1Line1G0:
        byte $00,$AA,$AA,$AC,$EC,$AA,$AA,$4C
Page1Line1G1:
        byte $00,$E0,$80,$80,$C0,$80,$80,$E0
Page1Line1G2:
        byte $00,$EA,$4A,$4E,$4E,$4E,$4E,$EA
Page1Line1G3:
        byte $00,$0A,$0A,$0E,$0E,$0E,$0E,$0A
Page1Line1G4:
        byte $00,$AC,$A2,$A2,$E4,$A8,$A8,$46
Page1Line1G5:
        byte $00,$A4,$A0,$A0,$E0,$A0,$A0,$40

Page1Line2G0:
        byte $00,$8A,$8A,$8C,$CC,$AA,$AA,$CC
Page1Line2G1:
        byte $00,$EC,$82,$82,$C4,$88,$88,$E6
Page1Line2G2:
        byte $00,$C0,$20,$20,$40,$80,$80,$60
Page1Line2G3:
        byte $00,$8E,$84,$84,$C4,$84,$84,$EE
Page1Line2G4:
        byte $00,$AE,$A8,$C8,$CC,$A8,$A8,$CE
Page1Line2G5:
        byte $00,$00,$00,$00,$00,$00,$00,$00

Page1Line3G0:
        byte $00,$44,$4A,$4A,$4A,$4A,$4A,$E4
Page1Line3G1:
        byte $00,$0A,$0A,$0A,$0E,$0A,$0A,$04
Page1Line3G2:
        byte $00,$64,$84,$84,$84,$84,$84,$6E
Page1Line3G3:
        byte $00,$E4,$44,$4A,$4A,$4A,$4A,$EA
Page1Line3G4:
        byte $00,$A4,$A4,$A4,$E4,$A4,$A4,$4E
Page1Line3G5:
        byte $00,$E0,$80,$80,$C0,$80,$80,$E0

Page1Line4G0:
        byte $00,$CA,$2A,$2A,$4E,$8A,$8A,$64
Page1Line4G1:
        byte $00,$4E,$48,$48,$4C,$48,$48,$EE
Page1Line4G2:
        byte $00,$EE,$88,$88,$88,$88,$88,$88
Page1Line4G3:
        byte $00,$E4,$44,$44,$44,$44,$44,$EE
Page1Line4G4:
        byte $00,$EC,$82,$82,$C4,$88,$88,$E6
Page1Line4G5:
        byte $00,$40,$00,$00,$00,$00,$00,$00

Page1Line5G0:
        byte $00,$00,$00,$00,$00,$00,$00,$00
Page1Line5G1:
        byte $00,$00,$00,$00,$00,$00,$00,$00
Page1Line5G2:
        byte $00,$00,$00,$00,$00,$00,$00,$00
Page1Line5G3:
        byte $00,$00,$00,$00,$00,$00,$00,$00
Page1Line5G4:
        byte $00,$00,$00,$00,$00,$00,$00,$00
Page1Line5G5:
        byte $00,$00,$00,$00,$00,$00,$00,$00

Page2Line0G0:
        byte $00,$6A,$8A,$8A,$8E,$8A,$8A,$6A
Page2Line0G1:
        byte $00,$A8,$A8,$A8,$EC,$AA,$AA,$4C
Page2Line0G2:
        byte $00,$4E,$48,$48,$4C,$48,$48,$EE
Page2Line0G3:
        byte $00,$A0,$A0,$C0,$C0,$A0,$A0,$C0
Page2Line0G4:
        byte $00,$4A,$AA,$AE,$AE,$AE,$AE,$4A
Page2Line0G5:
        byte $00,$E0,$80,$80,$C0,$80,$80,$E0

Page2Line1G0:
        byte $00,$EE,$88,$88,$8C,$88,$88,$8E
Page2Line1G1:
        byte $00,$AA,$AA,$AC,$EC,$AA,$AA,$4C
Page2Line1G2:
        byte $00,$A0,$A0,$E0,$E0,$E0,$E0,$A0
Page2Line1G3:
        byte $00,$A4,$AA,$AA,$EA,$AA,$AA,$A4
Page2Line1G4:
        byte $00,$A0,$E0,$E0,$A0,$A0,$A0,$A0
Page2Line1G5:
        byte $00,$E4,$44,$44,$44,$44,$44,$EE

Page2Line2G0:
        byte $00,$AE,$A8,$A8,$E8,$A8,$A8,$48
Page2Line2G1:
        byte $00,$E0,$80,$80,$80,$80,$80,$80
Page2Line2G2:
        byte $00,$A4,$EA,$EA,$AA,$AA,$AA,$A4
Page2Line2G3:
        byte $00,$AA,$AA,$CC,$C8,$AC,$AA,$CA
Page2Line2G4:
        byte $00,$C4,$20,$20,$40,$80,$80,$60
Page2Line2G5:
        byte $00,$00,$00,$00,$00,$00,$00,$00

Page2Line3G0:
        byte $00,$C8,$28,$28,$4C,$8A,$8A,$6C
Page2Line3G1:
        byte $00,$A6,$A8,$A8,$E8,$A8,$A8,$46
Page2Line3G2:
        byte $00,$E0,$80,$80,$C0,$80,$80,$E0
Page2Line3G3:
        byte $00,$6E,$A8,$A8,$AC,$88,$88,$6E
Page2Line3G4:
        byte $00,$4C,$42,$42,$44,$48,$48,$E6
Page2Line3G5:
        byte $00,$00,$00,$00,$00,$00,$00,$00

Page2Line4G0:
        byte $00,$4A,$4A,$4C,$4C,$4A,$4A,$EC
Page2Line4G1:
        byte $00,$E6,$48,$48,$48,$48,$48,$E6
Page2Line4G2:
        byte $00,$AE,$A4,$C4,$84,$C4,$A4,$AE
Page2Line4G3:
        byte $00,$EA,$8A,$8C,$CC,$8A,$8A,$EC
Page2Line4G4:
        byte $00,$44,$00,$00,$00,$00,$00,$00
Page2Line4G5:
        byte $00,$40,$00,$00,$00,$00,$00,$00

Page2Line5G0:
        byte $00,$00,$00,$00,$00,$00,$00,$00
Page2Line5G1:
        byte $00,$00,$00,$00,$00,$00,$00,$00
Page2Line5G2:
        byte $00,$00,$00,$00,$00,$00,$00,$00
Page2Line5G3:
        byte $00,$00,$00,$00,$00,$00,$00,$00
Page2Line5G4:
        byte $00,$00,$00,$00,$00,$00,$00,$00
Page2Line5G5:
        byte $00,$00,$00,$00,$00,$00,$00,$00

PromptMoreLineG0:
        byte $00,$A4,$AA,$AA,$AA,$EA,$EA,$A4
PromptMoreLineG1:
        byte $00,$AE,$A8,$C8,$CC,$A8,$A8,$CE
PromptMoreLineG2:
        byte $00,$44,$00,$00,$00,$00,$00,$00
PromptMoreLineG3:
        byte $00,$40,$00,$00,$00,$00,$00,$00
PromptMoreLineG4:
        byte $00,$00,$00,$00,$00,$00,$00,$00
PromptMoreLineG5:
        byte $00,$00,$00,$00,$00,$00,$00,$00

PromptGoLineG0:
        byte $00,$64,$AA,$AA,$AA,$8A,$8A,$64
PromptGoLineG1:
        byte $00,$40,$00,$40,$40,$40,$40,$40
PromptGoLineG2:
        byte $00,$00,$00,$00,$00,$00,$00,$00
PromptGoLineG3:
        byte $00,$00,$00,$00,$00,$00,$00,$00
PromptGoLineG4:
        byte $00,$00,$00,$00,$00,$00,$00,$00
PromptGoLineG5:
        byte $00,$00,$00,$00,$00,$00,$00,$00

Page0Text:
        byte <Page0Line0G0,>Page0Line0G0,<Page0Line0G1,>Page0Line0G1,<Page0Line0G2,>Page0Line0G2,<Page0Line0G3,>Page0Line0G3,<Page0Line0G4,>Page0Line0G4,<Page0Line0G5,>Page0Line0G5
        byte <Page0Line1G0,>Page0Line1G0,<Page0Line1G1,>Page0Line1G1,<Page0Line1G2,>Page0Line1G2,<Page0Line1G3,>Page0Line1G3,<Page0Line1G4,>Page0Line1G4,<Page0Line1G5,>Page0Line1G5
        byte <Page0Line2G0,>Page0Line2G0,<Page0Line2G1,>Page0Line2G1,<Page0Line2G2,>Page0Line2G2,<Page0Line2G3,>Page0Line2G3,<Page0Line2G4,>Page0Line2G4,<Page0Line2G5,>Page0Line2G5
        byte <Page0Line3G0,>Page0Line3G0,<Page0Line3G1,>Page0Line3G1,<Page0Line3G2,>Page0Line3G2,<Page0Line3G3,>Page0Line3G3,<Page0Line3G4,>Page0Line3G4,<Page0Line3G5,>Page0Line3G5
        byte <Page0Line4G0,>Page0Line4G0,<Page0Line4G1,>Page0Line4G1,<Page0Line4G2,>Page0Line4G2,<Page0Line4G3,>Page0Line4G3,<Page0Line4G4,>Page0Line4G4,<Page0Line4G5,>Page0Line4G5
        byte <Page0Line5G0,>Page0Line5G0,<Page0Line5G1,>Page0Line5G1,<Page0Line5G2,>Page0Line5G2,<Page0Line5G3,>Page0Line5G3,<Page0Line5G4,>Page0Line5G4,<Page0Line5G5,>Page0Line5G5

Page1Text:
        byte <Page1Line0G0,>Page1Line0G0,<Page1Line0G1,>Page1Line0G1,<Page1Line0G2,>Page1Line0G2,<Page1Line0G3,>Page1Line0G3,<Page1Line0G4,>Page1Line0G4,<Page1Line0G5,>Page1Line0G5
        byte <Page1Line1G0,>Page1Line1G0,<Page1Line1G1,>Page1Line1G1,<Page1Line1G2,>Page1Line1G2,<Page1Line1G3,>Page1Line1G3,<Page1Line1G4,>Page1Line1G4,<Page1Line1G5,>Page1Line1G5
        byte <Page1Line2G0,>Page1Line2G0,<Page1Line2G1,>Page1Line2G1,<Page1Line2G2,>Page1Line2G2,<Page1Line2G3,>Page1Line2G3,<Page1Line2G4,>Page1Line2G4,<Page1Line2G5,>Page1Line2G5
        byte <Page1Line3G0,>Page1Line3G0,<Page1Line3G1,>Page1Line3G1,<Page1Line3G2,>Page1Line3G2,<Page1Line3G3,>Page1Line3G3,<Page1Line3G4,>Page1Line3G4,<Page1Line3G5,>Page1Line3G5
        byte <Page1Line4G0,>Page1Line4G0,<Page1Line4G1,>Page1Line4G1,<Page1Line4G2,>Page1Line4G2,<Page1Line4G3,>Page1Line4G3,<Page1Line4G4,>Page1Line4G4,<Page1Line4G5,>Page1Line4G5
        byte <Page1Line5G0,>Page1Line5G0,<Page1Line5G1,>Page1Line5G1,<Page1Line5G2,>Page1Line5G2,<Page1Line5G3,>Page1Line5G3,<Page1Line5G4,>Page1Line5G4,<Page1Line5G5,>Page1Line5G5

Page2Text:
        byte <Page2Line0G0,>Page2Line0G0,<Page2Line0G1,>Page2Line0G1,<Page2Line0G2,>Page2Line0G2,<Page2Line0G3,>Page2Line0G3,<Page2Line0G4,>Page2Line0G4,<Page2Line0G5,>Page2Line0G5
        byte <Page2Line1G0,>Page2Line1G0,<Page2Line1G1,>Page2Line1G1,<Page2Line1G2,>Page2Line1G2,<Page2Line1G3,>Page2Line1G3,<Page2Line1G4,>Page2Line1G4,<Page2Line1G5,>Page2Line1G5
        byte <Page2Line2G0,>Page2Line2G0,<Page2Line2G1,>Page2Line2G1,<Page2Line2G2,>Page2Line2G2,<Page2Line2G3,>Page2Line2G3,<Page2Line2G4,>Page2Line2G4,<Page2Line2G5,>Page2Line2G5
        byte <Page2Line3G0,>Page2Line3G0,<Page2Line3G1,>Page2Line3G1,<Page2Line3G2,>Page2Line3G2,<Page2Line3G3,>Page2Line3G3,<Page2Line3G4,>Page2Line3G4,<Page2Line3G5,>Page2Line3G5
        byte <Page2Line4G0,>Page2Line4G0,<Page2Line4G1,>Page2Line4G1,<Page2Line4G2,>Page2Line4G2,<Page2Line4G3,>Page2Line4G3,<Page2Line4G4,>Page2Line4G4,<Page2Line4G5,>Page2Line4G5
        byte <Page2Line5G0,>Page2Line5G0,<Page2Line5G1,>Page2Line5G1,<Page2Line5G2,>Page2Line5G2,<Page2Line5G3,>Page2Line5G3,<Page2Line5G4,>Page2Line5G4,<Page2Line5G5,>Page2Line5G5

PromptMoreText:
        byte <PromptMoreLineG0,>PromptMoreLineG0,<PromptMoreLineG1,>PromptMoreLineG1,<PromptMoreLineG2,>PromptMoreLineG2,<PromptMoreLineG3,>PromptMoreLineG3,<PromptMoreLineG4,>PromptMoreLineG4,<PromptMoreLineG5,>PromptMoreLineG5

PromptGoText:
        byte <PromptGoLineG0,>PromptGoLineG0,<PromptGoLineG1,>PromptGoLineG1,<PromptGoLineG2,>PromptGoLineG2,<PromptGoLineG3,>PromptGoLineG3,<PromptGoLineG4,>PromptGoLineG4,<PromptGoLineG5,>PromptGoLineG5

PageTextLow: byte <Page0Text,<Page1Text,<Page2Text
PageTextHigh: byte >Page0Text,>Page1Text,>Page2Text
