#!/usr/bin/env python3
"""Generate the five independently authored Chapter One P1 display pages."""

from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "src"

OPTIONAL = (0x10, 0x18, 0x7C, 0xFE, 0x7C, 0x18, 0x10)
DISH = (0x3C, 0x60, 0xC0, 0xC0, 0x60, 0x3C, 0x18, 0x3C)
COLLECTIBLE = (0x38, 0x78, 0xF0, 0xF8, 0xF0, 0x78, 0x38)
EXIT = (0x3C, 0x7E, 0xC3, 0xDB, 0xDB, 0xC3, 0x3C)

# P1 must retain this object order, but every stage owns its own vertical
# cadence. Values are top rows followed by the seven positioning-service rows.
STAGES = {
    1: {
        "tops": (9, 29, 49, 77, 97, 123, 145, 161),
        "service": (23, 45, 65, 93, 115, 139, 159),
    },
    2: {
        "tops": (9, 31, 51, 75, 95, 119, 141, 157),
        "service": (23, 47, 67, 91, 111, 135, 155),
    },
    3: {
        "tops": (11, 33, 53, 75, 95, 117, 139, 155),
        "service": (25, 49, 67, 91, 109, 133, 153),
    },
    4: {
        "tops": (13, 33, 53, 79, 99, 121, 143, 159),
        "service": (27, 49, 67, 95, 113, 137, 157),
    },
    5: {
        "tops": (9, 29, 49, 83, 103, 125, 143, 159),
        "service": (23, 45, 63, 99, 117, 141, 157),
    },
}


def emit_bytes(values: list[int]) -> list[str]:
    return [
        "        byte " + ",".join(f"${value:02X}" for value in values[i : i + 16])
        for i in range(0, len(values), 16)
    ]


for stage, layout in STAGES.items():
    world = [0] * 176
    top_optional, top_a, top_c0, top_b, top_c1, top_c, top_c2, top_exit = layout["tops"]
    for top, sprite in (
        (top_optional, OPTIONAL),
        (top_a, DISH),
        (top_c0, COLLECTIBLE),
        (top_b, DISH),
        (top_c1, COLLECTIBLE),
        (top_c, DISH),
        (top_c2, COLLECTIBLE),
        (top_exit, EXIT),
    ):
        for row, value in enumerate(sprite):
            line = top + row * 2
            if line >= 176 or world[line]:
                raise SystemExit(f"Stage {stage} has an invalid object row at {line}")
            world[line] = value

    service = [0] * 176
    for code, line in enumerate(layout["service"], 1):
        if line % 2 == 0 or service[line]:
            raise SystemExit(f"Stage {stage} has an invalid service row at {line}")
        service[line] = code

    prefix = "" if stage == 1 else f"Stage{stage}"
    physical_bank = 7 if stage == 1 else 8 - stage
    lines = [
        "; Generated by tools/generate_stage_object_pages.py; do not hand-edit.",
        f"{prefix}WorldGraphics:",
        *emit_bytes(world),
        "",
        f"        ORG ${physical_bank:X}700",
        "        RORG $F700",
        f"{prefix}ServiceCode:",
        *emit_bytes(service),
        "",
    ]
    (SRC / f"thursdays-child-stage{stage}-objects.inc").write_text("\n".join(lines))

# Zone 2-3 keeps Stage 3's independent renderer bank but authors a new vertical
# cadence around the three center platforms. No service row overlaps an elastic
# color-control marker.
layout = {
    "tops": (11, 27, 49, 81, 99, 131, 147, 163),
    "service": (21, 43, 73, 97, 119, 145, 161),
}
world = [0] * 176
top_optional, top_a, top_c0, top_b, top_c1, top_c, top_c2, top_exit = layout["tops"]
for top, sprite in (
    (top_optional, OPTIONAL), (top_a, DISH), (top_c0, COLLECTIBLE),
    (top_b, DISH), (top_c1, COLLECTIBLE), (top_c, DISH),
    (top_c2, COLLECTIBLE), (top_exit, EXIT),
):
    for row, value in enumerate(sprite):
        line = top + row * 2
        if line >= 176 or world[line]:
            raise SystemExit(f"Zone 2-3 has an invalid object row at {line}")
        world[line] = value
service = [0] * 176
for code, line in enumerate(layout["service"], 1):
    if line % 2 == 0 or service[line]:
        raise SystemExit(f"Zone 2-3 has an invalid service row at {line}")
    service[line] = code
lines = [
    "; Generated by tools/generate_stage_object_pages.py; do not hand-edit.",
    "Stage3WorldGraphics:",
    *emit_bytes(world),
    "",
    "        ORG $5700",
    "        RORG $F700",
    "Stage3ServiceCode:",
    *emit_bytes(service),
    "",
]
(SRC / "thursdays-child-stage3-zone2-3-objects.inc").write_text("\n".join(lines))
